### ISSUE TITLE
syntax error, unexpected '?' in PHP7.0

### ISSUE THREAD

**Issue by elvispdosreis** [zendframework/zend-soap#46]
…\vendor\zendframework\zend-code\src\Reflection\DocBlock\Tag\VarTag.php69

 public function getVariableName() : ?string
    {
        return $this->variableName;
    }

![zend](https://user-images.githubusercontent.com/15267623/31881630-e821ad8a-b7c2-11e7-8d67-adec8cb51af8.PNG)

**Comment by webimpress** [comment]
@elvispdosreis What version of `zendframework/zend-code` are you using (`composer show`)? As I can see `VarTag` support has been added in [3.2.0](https://github.com/zendframework/zend-code/releases/tag/release-3.2.0) - PR [#41](https://github.com/zendframework/zend-code/pull/41) and it requires PHP 7.1.

**Comment by elvispdosreis** [comment]
"zendframework/zend-soap": "^2.6",

**Comment by webimpress** [comment]
@elvispdosreis sorry, I've asked for `zend-code`, not `zend-soap`. as you said, the issue seems to be in file:
```
 \vendor\zendframework\zend-code\src\Reflection\DocBlock\Tag\VarTag.php69
                       ^^^^^^^^^^
```

**Comment by elvispdosreis** [comment]
it seems that the zend-core version is incompatible with php7.0

{
    "name": "zendframework/zend-code",
    "description": "provides facilities to generate arbitrary code using an object oriented interface",
    "license": "BSD-3-Clause",
    "keywords": [
        "zf2",
        "code"
    ],
    "homepage": "https://github.com/zendframework/zend-code",
    "autoload": {
        "psr-4": {
            "Zend\\Code\\": "src/"
        }
    },
    "require": {
        **"php": "^7.1",**
        "zendframework/zend-eventmanager": "^2.6 || ^3.0"
    },
    "require-dev": {
        "ext-phar": "*",
        "doctrine/annotations": "~1.0",
        "zendframework/zend-stdlib": "^2.7 || ^3.0",
        "phpunit/phpunit": "^6.2.3",
        "zendframework/zend-coding-standard": "^1.0.0"
    },
    "suggest": {
        "doctrine/annotations": "Doctrine\\Common\\Annotations >=1.0 for annotation features",
        "zendframework/zend-stdlib": "Zend\\Stdlib component"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "branch-alias": {
            "dev-master": "3.2-dev",
            "dev-develop": "3.3-dev"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "ZendTest\\Code\\": "test/"
        }
    },
    "scripts": {
        "check": [
            "@cs-check",
            "@test"
        ],
        "upload-coverage": "coveralls -v",
        "cs-check": "phpcs",
        "cs-fix": "phpcbf",
        "test": "phpunit --colors=always",
        "test-coverage": "phpunit --colors=always --coverage-clover clover.xml"
    }
}

**Comment by webimpress** [comment]
@elvispdosreis as I said, since `zend-code 3.2.0` supports only PHP7.1. I have no idea how then you've install it. Please check your dependencies (you can share `composer show` results here) and run update  (`composer update`) to update your dependencies. Have you install with `--ignore-platform-reqs`? I can't see any issue with libraries, this is just problem with your installation.
